# Reading and writing `_bookdown.yml`.
#
# The package owns this file's shape but not its whole contents: users are free
# to add bookdown settings we know nothing about. Every write therefore
# round-trips unknown keys instead of regenerating the file from a template.

bookdown_config_path <- function(project) {
  fs::path(project, "_bookdown.yml")
}

output_config_path <- function(project) {
  fs::path(project, "_output.yml")
}

read_bookdown_config <- function(project) {
  path <- bookdown_config_path(project)
  if (!fs::file_exists(path)) {
    pub_abort(
      c(
        "Cannot read the project configuration.",
        x = "{.file _bookdown.yml} does not exist in {.path {project}}."
      ),
      class = "alberdilabr_error_no_config"
    )
  }
  config <- tryCatch(
    yaml::read_yaml(path),
    error = function(e) {
      pub_abort(
        c(
          "{.file _bookdown.yml} is not valid YAML.",
          x = conditionMessage(e),
          i = "Fix the syntax error and try again."
        ),
        class = "alberdilabr_error_bad_config"
      )
    }
  )
  if (!is.list(config)) {
    pub_abort(
      c(
        "{.file _bookdown.yml} must contain a YAML mapping of settings.",
        x = "Parsed to {.obj_type_friendly {config}} instead."
      ),
      class = "alberdilabr_error_bad_config"
    )
  }
  config
}

# Keys we generate, in the order we want to see them. Anything else the user
# added is appended afterwards, untouched.
config_key_order <- c(
  "book_filename", "delete_merged_file", "output_dir", "clean", "rmd_files"
)

write_bookdown_config <- function(project, config) {
  known <- intersect(config_key_order, names(config))
  extra <- setdiff(names(config), config_key_order)
  ordered <- config[c(known, extra)]

  lines <- c(
    "# Generated by alberdilabr. Chapter order is explicit and authoritative:",
    "# use add_chapter() / move_chapter() / remove_chapter() to change it,",
    "# or edit rmd_files by hand and run check_publication().",
    ""
  )
  for (key in names(ordered)) {
    value <- ordered[[key]]
    if (key == "rmd_files" || (length(value) > 1 && is.null(names(value)))) {
      lines <- c(lines, paste0(key, ":"))
      lines <- c(lines, paste0("  - ", yaml_scalar(value)))
    } else if (is.logical(value) && length(value) == 1 && !is.na(value)) {
      # yaml::as.yaml emits YAML 1.1 "yes"/"no"; write "true"/"false", which
      # every YAML version reads the same way.
      lines <- c(lines, paste0(key, ": ", tolower(as.character(value))))
    } else {
      # Let yaml handle nested structures we do not model ourselves.
      chunk <- yaml::as.yaml(stats::setNames(list(value), key))
      lines <- c(lines, sub("\n$", "", chunk))
    }
  }
  write_lines_atomic(lines, bookdown_config_path(project))
}

# Quote scalars only when YAML would otherwise misread them. Paths containing
# ":" or leading/trailing space are the realistic hazards.
yaml_scalar <- function(x) {
  x <- as.character(x)
  needs_quote <- grepl('[:#"\']|^[[:space:]]|[[:space:]]$|^$', x)
  ifelse(needs_quote, paste0('"', gsub('"', '\\\\"', x), '"'), x)
}

# Chapter listing -------------------------------------------------------------

config_rmd_files <- function(config) {
  files <- config$rmd_files
  if (is.null(files)) {
    return(character(0))
  }
  as.character(unlist(files, use.names = FALSE))
}

# The chapter table is the single in-memory view every command works from:
# position in rmd_files, path on disk, parsed number and slug.
config_chapters <- function(config) {
  files <- config_rmd_files(config)
  chapters <- files[files != "index.Rmd"]
  data.frame(
    position = seq_along(chapters),
    path = chapters,
    number = parse_chapter_number(chapters),
    slug = parse_chapter_path(chapters),
    stringsAsFactors = FALSE
  )
}

# Resolve a user-supplied chapter reference (slug, filename or full path) to a
# row of the chapter table. Ambiguity and absence are both hard errors.
resolve_chapter <- function(config, chapter, call = rlang::caller_env()) {
  if (!rlang::is_string(chapter)) {
    pub_abort(
      "{.arg chapter} must be a single string naming a chapter.",
      class = "alberdilabr_error_type",
      call = call
    )
  }
  tbl <- config_chapters(config)
  if (nrow(tbl) == 0) {
    pub_abort(
      c(
        "Cannot find chapter {.val {chapter}}: the project has no chapters yet.",
        i = "Add one with {.fn add_chapter}."
      ),
      class = "alberdilabr_error_no_chapter",
      call = call
    )
  }
  hit <- which(
    tbl$slug == chapter |
      tbl$path == chapter |
      fs::path_file(tbl$path) == chapter |
      fs::path_ext_remove(fs::path_file(tbl$path)) == chapter
  )
  if (length(hit) == 0) {
    known <- tbl$slug[!is.na(tbl$slug)]
    pub_abort(
      c(
        "Cannot find chapter {.val {chapter}} in {.file _bookdown.yml}.",
        i = if (length(known)) "Registered chapters: {.val {known}}." else NULL
      ),
      class = "alberdilabr_error_no_chapter",
      call = call
    )
  }
  if (length(hit) > 1) {
    pub_abort(
      c(
        "Chapter reference {.val {chapter}} is ambiguous.",
        x = "It matches {.val {tbl$path[hit]}}.",
        i = "Use the full path to disambiguate."
      ),
      class = "alberdilabr_error_ambiguous_chapter",
      call = call
    )
  }
  tbl[hit, , drop = FALSE]
}
